encyclopedia/urls.py
from django.urls import path

from . import views

app_name= "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    #path("content",views.content,name="content"),
    path("wiki",views.wiki,name="wiki"),
    path("wiki/<str:name>",views.wiki,name="wiki"),
    path("wikiSearch",views.wikiSearch,name="wikiSearch"),
    path("newPage",views.newPage,name="newPage"),
    path("newPageError",views.newPageError,name="newPageError"),
    path("editPage/<str:name>",views.editPage,name="editPage"),
    path("editPage",views.editPage,name="editPage"),
    path("randomPage",views.randomPage,name="randomPage")
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

from . import util

from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from string import Template

import markdown2

import re

import random

def writetofile(name,entryBody):
    file1 = open(f"encyclopedia/templates/wiki/{name}.html","w")
    file1.write('{% extends "encyclopedia/layout.html" %}\n')
    file1.write('{% block body %}\n')
    file1.write(entryBody)
    #editLink=f"<a href=\"{% url 'encyclopedia:editPage',{"name":{name}} %}\">Edit Page</a>"
    #editLink=f"<a href=\"{% url 'encyclopedia:editPage' name=name %}\">Edit Page</a>"
    #editLink=f"<a href=\"{% url 'encyclopedia:editPage' name='{name}' %}\">Edit Page</a>"
    #editLink="<a href=\"{% url 'encyclopedia:editPage' name='{}' %}\">Edit Page</a>".format(name)
    #editLink="<a href=\"{\% url 'encyclopedia:editPage',{'name': %s} \%}\">Edit Page</a>".format(name)
    #editLink = Template("<a href=\"{% url 'encyclopedia:editPage' , {name:'$name' }} %}\">Edit Page</a>")
    editLink = Template("<a href=\"{% url 'encyclopedia:editPage' name='$name'  %}\">Edit Page</a>")
    editLink=editLink.substitute(name=name)
    print(editLink)
    file1.write(editLink)
    file1.write('\n{% endblock %}')

    file1.close()


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def newPageError(request):
    return render(request, "encyclopedia/newpageerror.html")

def displaypage(request,name):
    entryBody=util.get_entry(name)

    print(entryBody)
    if entryBody:
        entryBody= markdown2.markdown(entryBody)
        writetofile(name,entryBody)
        #file1 = open(f"encyclopedia/templates/wiki/{name}.html","w")
        #file1.write('{% extends "encyclopedia/layout.html" %}\n')
        #file1.write('{% block body %}\n')
        #file1.write(entryBody)
        #file1.write('\n{% endblock %}')

        #file1.close()
        return HttpResponseRedirect(f"wiki/{name}")
    else:
        return HttpResponseRedirect("encyclopedia/content.html", {
            "content": None
        })

#def content(request):
def wiki(request,name):
    #name=request.GET.get('name')
    entryBody=util.get_entry(name)


    if entryBody:
        entryBody= markdown2.markdown(entryBody)
        writetofile(name,entryBody)
        #file1 = open(f"encyclopedia/templates/wiki/{name}.html","w")
        #file1.write('{% extends "encyclopedia/layout.html" %}\n')
        #file1.write('{% block body %}\n')
        #file1.write(entryBody)
        #file1.write('\n{% endblock %}')

        #file1.close()
        return render(request, f"wiki/{name}.html")
    else:
        return render(request, "encyclopedia/content.html", {
            "content": None
        })
    

def wikiSearch(request):

    if request.method=="POST":
        name=request.POST['q']
        entryBody=util.get_entry(name)
        if entryBody:
            entryBody= markdown2.markdown(entryBody)
            writetofile(name,entryBody)
            #file1 = open(f"encyclopedia/templates/wiki/{name}.html","w")
            #file1.write('{% extends "encyclopedia/layout.html" %}\n')
            #file1.write('{% block body %}\n')
            #file1.write(entryBody)
            #file1.write('\n{% endblock %}')
            #file1.close()
            #return render(request, f"wiki/{name}.html")
            return HttpResponseRedirect(f"wiki/{name}")
        else:
            entryList=util.list_entries()
            matchEntryList = []
            for entry in entryList:
                match= re.search(name,entry,re.I)
                if match:
                    matchEntryList.append(entry)
                else:
                    pass
                    #matchEntryList.append(entry)

            #print(matchEntryList)
            if matchEntryList:
                return render(request, "encyclopedia/search.html", {
                    "entries": matchEntryList
                })
            else:

                return render(request, "encyclopedia/content.html", {
                    "content": None
            })    
    

class NewTaskForm(forms.Form):
    title=forms.CharField(label="New Page Title",empty_value="Page Title",max_length=100)
    body=forms.CharField(label="Page Body",widget=forms.Textarea)
    #priority = forms.IntegerField(label="Priority",min_value=1,max_value=10)

def newPage(request):
    if request.method=="POST":
        form=NewTaskForm(request.POST)
        if form.is_valid():
            title=form.cleaned_data["title"]
            body=form.cleaned_data["body"]
            print(title)
            print(body)
            entryBody=util.get_entry(title)
            if entryBody:
                return HttpResponseRedirect(reverse("encyclopedia:newPageError"))
            else:
                newfile= open(f"entries/{title}.md","w")
                newfile.write(body)
                newfile.close()

                entryBody=util.get_entry(title)
                entryBody= markdown2.markdown(entryBody)
                #file1 = open(f"encyclopedia/templates/wiki/{title}.html","w")
                #file1.write('{% extends "encyclopedia/layout.html" %}\n')
                #file1.write('{% block body %}\n')
                #file1.write(entryBody)
                #file1.write('\n{% endblock %}')
                #file1.close()
                writetofile(title,entryBody)
                #return render(request, f"wiki/{title}.html")
                return HttpResponseRedirect(f"wiki/{title}")

        else:
            return render(request,"encyclopedia/newpage.html",{
                "form":form
            })
    return render(request, "encyclopedia/newpage.html",{"form": NewTaskForm()}) 

class EditForm(forms.Form):

    #def initial(self,name):
    #    self.titleName==name
    #def __init__(name):
    
        
        #self.title=forms.CharField(label="Page Title",initial="test"   ,max_length=100)
        #self.body=forms.CharField(label="Page Body",widget=forms.Textarea,initial="sample body")
    title=forms.CharField(label="Page Title" ,max_length=100)
    body=forms.CharField(label="Page Body",widget=forms.Textarea)
    print("test 3")
    

def editPage(request,name):
    

    if request.method=="POST":
        print("post test 1")
        form = EditForm(request.POST)
        print("post test 2")
        if form.is_valid():
            title=form.cleaned_data["title"]
            body=form.cleaned_data["body"]
            print(title)
            print(body)


            newfile= open(f"entries/{title}.md","w")
            newfile.write(body)
            newfile.close()

            entryBody=util.get_entry(title)
            entryBody= markdown2.markdown(entryBody)
            #file1 = open(f"encyclopedia/templates/wiki/{title}.html","w")
            #file1.write('{% extends "encyclopedia/layout.html" %}\n')
            #file1.write('{% block body %}\n')
            #file1.write(entryBody)
            #file1.write('\n{% endblock %}')
            #file1.close()
            writetofile(title,entryBody)
            #return render(request, f"wiki/{title}.html")
            #return HttpResponseRedirect(f"wiki/{title}")


            #return HttpResponseRedirect(f"wiki/{title}")
            return render(request,f"wiki/{title}.html")
        else:
            return render(request,"encyclopedia/editpage.html",{
                "form":form
            })
            


    
    entryBody=util.get_entry(name)
    
    return render(request,"encyclopedia/editpage.html",{"name": name,"form": EditForm(initial={'title':name, 'body':entryBody})})
    

def randomPage(request):
    entries=util.list_entries()
    

    return displaypage(request,random.choice(entries))

encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    
 <h1>Entry Not Found</h1>
    
{% endblock %}

encyclopedia/templates/encyclopedia/editpage.html
    {% extends "encyclopedia/layout.html" %}

    {% block title %}
        Encyclopedia
    {% endblock %}

    {% block body %}
        <h1>Edit     Page</h1>
        
        <form action="{% url 'encyclopedia:editPage' name=name  %}" method="post" >
            {% csrf_token %}
            {{ form }}
            
            <input type="submit" value="Save Page">
        </form>
        

    {% endblock %}

encyclopedia/templates/encyclopedia/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, {{name}}!</h1>
    </body>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            
            <li>
                
                <!--a href="wiki/{{entry}}">{{ entry }}</a>-->
                <a href="wiki/{{entry}}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:wikiSearch' %}" method="post" >
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form action="{% url 'encyclopedia:newPage' %}" method="post" >
        {% csrf_token %}
        {{ form }}
        
        <input type="submit" value="Save Page">
    </form>
    

{% endblock %}

encyclopedia/templates/encyclopedia/newpageerror.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    
 <h1>Entry Already Exist</h1>
    
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            
            <li>
                
                <!--a href="wiki/{{entry}}">{{ entry }}</a>-->
                <a href="wiki/{{entry}}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/wiki/CSS.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>CSS</h1>

<p>CSS is a language that can be used to add style to an <a href="/wiki/HTML">HTML</a> page.</p>
<a href="{% url 'encyclopedia:editPage' name='CSS'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/Django.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>Django</h1>

<p>Django is a web framework written using <a href="/wiki/Python">Python</a> that allows for the design of web applications that generate <a href="/wiki/HTML">HTML</a> dynamically.</p>
<a href="{% url 'encyclopedia:editPage' name='Django'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/Git.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>Git</h1>

<p>Git is a version control tool that can be used to keep track of versions of a software project.</p>

<h2>GitHub</h2>

<p>GitHub is an online service for hosting git repositories.</p>
<a href="{% url 'encyclopedia:editPage' name='Git'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/HTML.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li>headings</li>
<li>paragraphs</li>
<li>lists</li>
<li>links</li>
<li>and more!</li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
<a href="{% url 'encyclopedia:editPage' name='HTML'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/Python.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>Python</h1>

<p>Python is a programming language that can be used both for writing <strong>command-line scripts</strong> or building <strong>web applications</strong>.</p>
<a href="{% url 'encyclopedia:editPage' name='Python'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/ewew.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>Django</h1>

<p>Django is a web framework written using <a href="/wiki/Python">Python</a> that allows for the design of web applications that generate <a href="/wiki/HTML">HTML</a> dynamically.</p>
<a href="{% url 'encyclopedia:editPage' name='ewew'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:wikiSearch' %}" method="post" >
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/wiki/omban.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li><p>headings</p></li>
<li><p>paragraphs</p></li>
<li><p>lists</p></li>
<li><p>links</p></li>
<li><p>and more!</p></li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
<a href="{% url 'encyclopedia:editPage' name='omban'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/test1.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li><p>headings</p></li>

<li><p>paragraphs</p></li>

<li><p>lists</p></li>

<li><p>links</p></li>

<li><p>and more!</p></li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
<a href="{% url 'encyclopedia:editPage' name='test1'  %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/wiki/test2.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li><p>headings</p></li>
<li><p>paragraphs</p></li>
<li><p>lists</p></li>
<li><p>links</p></li>
<li><p>and more!</p></li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
<a href="{% url 'encyclopedia:editPage' name='test2'  %}">Edit Page</a>
{% endblock %}